server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:          
          uri: https://github.com/NikhilGanage/spring-cloud-config.git
          search-paths: '{application}'
