management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      default-filters:
      - name: CustomPreFilter
      - name: CustomPostFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
