#this configuration registers to eureka server

server:
  port: 6070
  
spring:
  application:
    name: review-service
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer1:8765/eureka

    
